# Generated by Django 3.0.8 on 2020-07-30 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=550, null=True)),
                ('company_address', models.CharField(blank=True, max_length=550, null=True)),
                ('company_city', models.CharField(blank=True, max_length=550, null=True)),
                ('company_country', models.CharField(blank=True, max_length=550, null=True)),
                ('client_name', models.CharField(blank=True, max_length=550, null=True)),
                ('client_address', models.CharField(blank=True, max_length=550, null=True)),
                ('client_city', models.CharField(blank=True, max_length=550, null=True)),
                ('client_country', models.CharField(blank=True, max_length=550, null=True)),
                ('invoice_number', models.IntegerField(blank=True, default=0, verbose_name='invoice_number')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='freelancer')),
            ],
        ),
    ]
