# Generated by Django 3.0.8 on 2020-08-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0002_productmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='invoiceItemsModel',
        ),
        migrations.RenameField(
            model_name='invoicemodel',
            old_name='freelancer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='feedback',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='sales_tax',
            field=models.IntegerField(blank=True, default=0, verbose_name='invoice_number'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='subtotal',
            field=models.IntegerField(blank=True, default=0, verbose_name='invoice_number'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='terms',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
